version: '3.8'

services:
  mysqldb:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: stationSki
    ports:
      - 3307:3306  # Expose MySQL port on the host
    volumes:
      - db:/var/lib/mysql
    networks:
      - my-network

  app:
    build: ./
    ports:
      - 8089:8089
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url": "jdbc:mysql://mysqldb:3306/stationSki?createDatabaseIfNotExist=true",
        "spring.datasource.username": "root",
        "spring.datasource.password": "${MYSQL_ROOT_PASSWORD}",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update",
        "server.servlet.context-path" : "/api",
        "server.port" : 8089,
        "spring.mvc.format.date" : "yyyy-MM-dd",
        "spring.jpa.show-sql" : true,
        "logging.level.root" : "info",
        "logging.pattern.console" : "= %d{yyyy-MM-dd HH:mm:ss} -  %-5level - %logger{45} - %msg %n"
      }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
    restart: always
    networks:
      - my-network

volumes:
  db:

networks:
  my-network:
    external: false